### ISSUE TITLE
time:0.2.7  cannot find function `now` and `strftime` in crate `time`   

### ISSUE THREAD

**Issue by myishuohuo** [mikispag/bitiodine#19]
error[E0425]: cannot find function `now` in crate `time`
  --> src\main.rs:59:27
   |
59 |             let t = time::now();
   |                                not found in `time`

error[E0425]: cannot find function `strftime` in crate `time`
  --> src\main.rs:63:23
   |
63 |                 time::strftime("%Y-%m-%d %H:%M:%S", &t).unwrap(),
   |                               not found in `time`

**Comment by myishuohuo** [comment]
Has been resolved using version 0.1.42

**Comment by htitme** [comment]
> Has been resolved using version 0.1.42

I meet the same problem.  How to use version 0.1.42

**Comment by htitme** [comment]
> Has been resolved using version 0.1.42

Edit the cargo.lock?

**Comment by hanminglei** [comment]
@myishuohuo can you tell me the exact version of 0.1.42, I can't find it, now I install 1.44.0 in my PC, and I have the same problem with you. Thank you for your help.

**Comment by xingyushu** [comment]
> Has been resolved using version 0.1.42

I meet the same problem,how should I change the version? is it in the Cargo.toml "time = ">=0.1.42"  and excute " cargo build",
but it doesn't work.

**Comment by mikispag** [comment]
Should be fixed now.

**Comment by rafialhamd** [comment]
The problem still happens in time = "0.3.41".

**Error:**
error[E0425]: cannot find function `now` in crate `time`

**Comment by rafialhamd** [comment]
The problem still happens in time = "0.3.41".
Don't have permission to re-open. So created new issue [here](https://github.com/mikispag/bitiodine/issues/23).
